#!/bin/bash

unify_len() {
    local stdin="$(cat /dev/stdin)"

    # Pad each line with trailing spaces so that they are the same length
    local longest="$(echo "$stdin" | awk '{print length}' | sort -n | tail -1)"
    local len spaces
    echo "$stdin" | while IFS= read -r line; do
        len="$(echo "$line" | awk '{print length}')"
        spaces="$(printf "%$((longest-len))s")"
        echo "${line}${spaces}"
    done
}


fleur_de_lis_str="$(cat <<'EOF'

             8
           .d8b.
       _.d8888888b._
     .88888888888888b.
    d88888888888888888b
    8888888888888888888
    Y88888888888888888P
     'Y8888888888888P'
   _..._ 'Y88888P' _..._
 .d88889b. Y888P .d88888b.
d888888888b 888 d88888888b
888P  `Y8888888888P'  Y888
 b8b    Y88888888P    d8Y
  `"'  #############  '"`
         dP d8b Yb
     Ob=dP d888b Yb=dO
      `"` O88888O `"`
   jgs     'Y8P'
             '
     by: Joan G. Stark
EOF
)"

fleur_de_lis=()
while IFS= read -r line; do
    fleur_de_lis+=( "$line" )
done < <(unify_len <<< "$fleur_de_lis_str")


hostname="Hostname...: $(hostname)"
ext_ip="Internal IP: $(ip route get 1 |
                       grep -oE '192\.168(\.[0-9]{1,3}){2}' |
                       grep -v '^192\.168\.1\.1$')"
int_ip="External IP: $(cat /etc/update-motd.d/pretty-header-ext-ip.txt)"
time="Time.......: $(date +%r)"
date="Date.......: $(date +"%a, %b %e, %Y")"
weather="Weather....: $(cat /etc/update-motd.d/pretty-header-weather.txt)"


# Draw ascii art box around info
in_box="${hostname}
${int_ip}
${ext_ip}
${time}
${date}
${weather}"
box="\n\n\n\n\n$(echo -e "$in_box" | boxes -d parchment -p h2)"
info=()
while IFS= read -r line; do
    info+=( "$line" )
done < <(echo -e "$box" | unify_len)


# Pick random seed for lolcat
seeds=( 39 49 60 )
s="${seeds[$((RANDOM % 3))]}"

# Zip fleur_de_lis and box, center it, and give it color
for ((i=0; i<${#fleur_de_lis[@]}; i++)); do
    echo "${fleur_de_lis[i]}     ${info[i]}"
done | unify_len | figlet -ctf term | /usr/games/lolcat -fS "$s"
