#!/bin/bash

int_ip() {
    local all_ifaces=(
        $(ip link | awk '/^[0-9]/ {print $2}' | tr -d : | grep -v '^lo$')
    )

    # Attempt to get the internal ip of each network interface
    local -a has_ip ips
    for iface in "${all_ifaces[@]}"; do
        ip="$(
            ip -4 -o a show "$iface" |
            grep -Po '(?<=inet )[0-9]+(\.[0-9]+){3}/[0-9]+'
        )"
        if [[ -n "$ip" ]]; then
            has_ip+=( "$iface" )
            ips+=( "$ip" )
        fi
    done

    # If there are multiple ips label each one with its iface name
    local output
    for i in "${!ips[@]}"; do
        (( "$i" > 0 )) &&
            output+='\n             '
        (( "${#ips[@]}" > 1 )) &&
            output+="${has_ip[i]}: "
        output+="${ips[i]}"
    done

    echo "$output"
}

unify_len() {
    local stdin="$(cat /dev/stdin)"

    # Pad each line with trailing spaces so that they are the same length
    local longest="$(echo "$stdin" | awk '{print length}' | sort -n | tail -1)"
    local len spaces
    echo "$stdin" | while IFS= read -r line; do
        len="$(echo "$line" | awk '{print length}')"
        spaces="$(printf "%$((longest-len))s")"
        echo "${line}${spaces}"
    done
}


fleur_de_lis_str="$(cat <<'EOF'

             8
           .d8b.
       _.d8888888b._
     .88888888888888b.
    d88888888888888888b
    8888888888888888888
    Y88888888888888888P
     'Y8888888888888P'
   _..._ 'Y88888P' _..._
 .d88889b. Y888P .d88888b.
d888888888b 888 d88888888b
888P  `Y8888888888P'  Y888
 b8b    Y88888888P    d8Y
  `"'  #############  '"`
         dP d8b Yb
     Ob=dP d888b Yb=dO
      `"` O88888O `"`
   jgs     'Y8P'
             '
     by: Joan G. Stark
EOF
)"

fleur_de_lis=()
while IFS= read -r line; do
    fleur_de_lis+=( "$line" )
done < <(unify_len <<< "$fleur_de_lis_str")


distro="$(lsb_release -s -d)"
hostname="$(hostname)"
int_ip="$(int_ip)"
ext_ip="$(cat /etc/update-motd.d/pretty-header-ext-ip.txt)"
time="$(date +%r)"
date="$(date +"%a, %b %e, %Y")"
weather="$(cat /etc/update-motd.d/pretty-header-weather.txt)"


in_box="$(cat <<EOF
Distro.....: ${distro}
Hostname...: ${hostname}
Internal IP: ${int_ip}
External IP: ${ext_ip}
Time.......: ${time}
Date.......: ${date}
Weather....: ${weather}
EOF
)"
# Draw ascii art box around info
box="\n\n\n\n\n$(echo "$in_box" | HOME=~ boxes -d parchment -p h2)"
info=()
while IFS= read -r line; do
    info+=( "$line" )
done < <(echo -e "$box" | unify_len)


# Pick random seed for lolcat
seeds=( 39 49 60 )
s="${seeds[$((RANDOM % 3))]}"

# Zip fleur_de_lis and box, center it, and give it color
for ((i=0; i<${#fleur_de_lis[@]}; i++)); do
    echo "${fleur_de_lis[i]}     ${info[i]}"
done | unify_len | /usr/games/lolcat -fS "$s"
