#!/bin/bash

# - Putting the message in a variable trims trailing newlines
# - sed script 1: Remove leading newlines
# - sed script 2: Remove comments and patch
msg="$(cat "$1" | sed '/./,$!d; /^# Please enter the commit message/,$d')"

# The number of characers in msg
msg_len="$(echo -n "${msg}" | wc -m)"

if (( msg_len > 50 )); then
    echo "Commit message too long ($msg_len/50)" >&2
    exit 1
fi
